<div class='title'>Création <?=implode('&nbsp;', $models)?></div>
<form id='<?=$this->router->getActionName()?>Form' class='template action' action="<?=implode(' ', $models)?>" actionType='submit' actionName='validForm'>
    <div class='content'>
        <? foreach($models as $model): ?>
            <?=Phalcon\Builder\Form::getFields($model)?>
        <? endforeach; ?>
    </div>
    <div class='actionContainer'>
        <button id='cancel' class='action form' actionName='cancelForm'>Annuler</button>
        <button id='create' class='form'>Créer</button>
    </div>
</form>