<div class='title'>Models Index</div>
<? foreach($models as $index => $list): ?>
    <fieldset>
        <legend>
            <?=ucfirst($index)?>
        </legend>
        <? foreach($list as $model): ?>
            <?
                $name = Phalcon\Text::camelize($model);
            ?>
            <div>
                <a target='_blank' href="/<?=APP?>/scrud/<?=$name?>/search">
                    <?=$name?>
                </a>
            </div>
            <?             
                $name::getRelations('hasOne');
                foreach(Phalcon\Builder\Form::$relations as $relation):
            ?>
                <div>
                    <a target='_blank' href="/<?=APP?>/scrud/<?=$name?> <?=$relation['model']?>/search">
                        <?=$name?> <?=$relation['model']?>
                    </a>
                </div>
            <? endforeach; ?>
        <? endforeach; ?>
    </fieldset>
<? endforeach; ?>