<div class='title'>
    Edition <?=implode('&nbsp;', $models)?>
    <img id="searchItem" class='action' title="Rechercher" src="/lib/scrud/public/img/form/search.png" action-data='<?=json_encode([
        'class'=>$manager,
        'fn'=>'redirect',
        'data'=>['path'=>'scrud/'.$actionModel.'/search'] 
    ])?>' /> 
</div>
<form id='<?=$this->router->getActionName()?>Form' class='template action' action="<?=implode(' ', $models)?>" action-data='<?=json_encode([
    'class'=>$manager,
    'type'=>'submit',
    'name'=>'validForm'
])?>'>
    <div class='content'>
        <?=Phalcon\Tag::hiddenField($primaryKey)?>
        <? foreach($models as $model): ?>
            <?=Phalcon\Builder\Form::getFields($model)?>
        <? endforeach; ?>
    </div>
    <div class='actionContainer'>
        <button id='cancel' class='action form' preventDefault action-data='<?=json_encode([
            'class'=>$manager,
            'fn'=>'redirect',
            'data'=>['path'=>'scrud/'.$actionModel.'/search']
        ])?>'>Annuler</button>
        <button id='create' class='form'>Modifier</button>
    </div>
</form>