<? foreach($rows as $row): ?>
    <? $model = $models[0]; ?>
    <tr class='action' action-data='<?=json_encode([
        'class'=>'SearchScrudManager',
        'fn'=>'redirect',
        'data'=>['path'=>'scrud/'.$actionModel.'/read?'.$model::getPrimaryKey().'='.$row->$primaryKey] 
    ])?>'>
        <td>
            <input title='Sélectionner pour suppression' type='checkbox' class='action' stopPropagation id="<?=$row->$primaryKey?>" />
        </td>
        <? foreach($models as $model): ?>
            <? foreach($model::getColumnsMap() as $id => $name): ?>
                <?
                    if(isset($includes) && !in_array($id, $includes)){
                        continue;
                    }
                ?>
                <td id='<?=$id?>' alt='<?=$model?>' title='<?=str_replace(['_id', 'is_'],['', ''],$name)?>'>
                    <? if(!isset($row->$id)): ?>
                        <?
                            $modelName = $models[0];
                            $fieldName = $modelName::getReferencedField($model);                        
                            $modelName = Phalcon\Text::uncamelize($model).substr($fieldName, strpos($fieldName, '_'));
                        ?>
                        <?=$row->$modelName->$id?>
                    <? elseif($model::getType($id) === 'tinyint'): ?>
                        <?=((int)$row->$id === 0) ? 'Non' : 'Oui'?>
                    <? elseif(isset(Phalcon\Builder\Form::$relations[$id])): ?>
                        <?
                            $modelName = Phalcon\Builder\Form::$relations[$id]['model'];
                            $fieldName = $modelName::getPrefix().'_name';
                            $modelName = Phalcon\Text::uncamelize(Phalcon\Builder\Form::$relations[$id]['model']).'_'.$name;
                            if(!isset($row->$modelName)){
                                $fn = 'findFirstBy'.ucfirst($id);
                                $fieldName =  $model::getPrefix().'_name';
                                $val = $model::$fn($row->$id)->$fieldName;
                            } else {
                                $val = $row->$modelName->$fieldName;
                            }
                        ?>
                        <?=$val?>
                    <? else: ?>
                        <?=$row->$id?>
                    <? endif; ?>
                </td>
            <? endforeach; ?>
        <? endforeach; ?> 
    </tr>
<? endforeach; ?>