<html lang="<?=$lang?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <?=$this->assets->outputJs('bowerjs')?>
        <? foreach($this->assets->collection('mjs')->getAssets() as $asset): ?>
            <script type="module" src="/<?=$this->assets->collection('mjs')->getPrefix().$asset->getPath()?>?v=<?=$this->config->version?>"></script>
        <? endforeach; ?>
        <?=$this->assets->outputJs('libjs')?>        
        <?=$this->assets->outputCss('css')?>
        <?=$this->assets->outputCss('libcss')?>
    </head>
    <body app="<?=APP?>" version="<?=$this->config->version?>">
        <?=$this->getContent()?>
    </body>
</html>