<html lang="<?=$lang?>">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?=$this->assets->outputJs('bowerjs')?>
        <?=$this->assets->outputJs('js')?>
        <?=$this->assets->outputJs('libjs')?>        
        <?=$this->assets->outputCss('css')?>
        <?=$this->assets->outputCss('libcss')?>
    </head>
    <body app="<?=APP?>" version="<?=$this->config->version?>">
        <?=$this->getContent()?>
    </body>
</html>